---
- name: AWS - Criando EC2
  hosts: localhost
  tasks:
    - name: Security Group
      ec2_group:
        name: webserver
        description: Regras de Firewall - DevSecOps
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 186.230.35.154/32

    - name: Criando SSH
      ec2_key:
        name: devsecops
        key_material: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDb+g1cRQ7S+J5e+peW1FH+FUbTmIr7vYuzk8w2H9QIPBr8fjRTkLYt19TAZWagyjJXK1dnq/Iudi4wVF53OQEzoyDt9nnNEvxyf76rh1dn43y4+fYJaeA4RLWJDRLZ8UbrkF141ISM0m1AlSxUniXHTG0Az+MyB87PgahEQw95OelJfbBpo1CPW8uSIQAPLdIPpR/hjyX+P9eN6tlif/zjZ4J3UiTcgXyJf+8NnO3jv7QShyMtLg1iMAgu2FRu+TmrKbzWMm0GgQ+thDVRWvFfPvPYPRnPthLg8TRabAu4gu1bweV+cFeLlq+ZCOHafQJcapsld97Cj57pENT5T42p'

    - name: Criando a Instancia
      ec2:
        key_name: devsecops
        instance_type: t2.micro
        region: us-east-1
        image: ami-5a809b25
        wait: yes
        group: webserver
        user_data: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install nginx -y
          echo "POBREFLIX É SHOW!" > /var/www/html/index.html
